## Leer data de una Base de Datos

### Cargo Paquetes Iniciales

In [2]:
from functions.create_db import load_data, dict_Empresas, write_sql_main
import pandas as pd
import datetime as dt
import sqlite3

### Cargo Datos (Clase Anterior)

In [3]:
df = load_data(dict_Empresas, start=dt.date(2024,1,1))

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Archivo Apple cargado exitosamente.

[*********************100%***********************]  1 of 1 completed

Archivo Microsoft cargado exitosamente.

[*********************100%***********************]  1 of 1 completed

Archivo Meta cargado exitosamente.

[*********************100%***********************]  1 of 1 completed

Archivo Tesla cargado exitosamente.

In [4]:
df

,Date,Close,High,Low,Open,Volume,Empresa,TKT
0,2024-01-02,183.562180,186.330843,181.831767,185.055273,82488700,Apple,AAPL
1,2024-01-03,182.187729,183.799489,181.376900,182.158066,58414500,Apple,AAPL
2,2024-01-04,179.873947,181.040733,178.855477,180.111251,71983600,Apple,AAPL
3,2024-01-05,179.152130,180.714448,178.153440,179.953077,62379700,Apple,AAPL
4,2024-01-08,183.483078,183.522639,179.468523,180.051916,59144500,Apple,AAPL
...,...,...,...,...,...,...,...,...
599,2026-05-22,426.010010,431.510010,420.510010,422.670013,46104700,Tesla,TSLA
600,2026-05-26,433.589996,435.200012,426.119995,430.260010,45658900,Tesla,TSLA
601,2026-05-27,440.359985,445.600006,435.519989,442.890015,44656500,Tesla,TSLA
602,2026-05-28,442.100006,443.959991,436.299988,437.619995,32435000,Tesla,TSLA
603,2026-05-29,435.790009,441.070007,428.140015,439.850006,45059400,Tesla,TSLA

In [6]:
write_sql_main(DB='../local/database/stock_db.db',
               df = df,
               table="main")

Connected to SQLite
The SQLite connection is closed

'ok'

### Leer Info de una Base de Datos

In [7]:
#Me conecto a la Base de Datos
conn = sqlite3.connect('../local/database/stock_db.db')

In [8]:
#¿Como ver las tablas de una BD?
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
tables.head()

   name
0  main

In [9]:
#¿Como ver las tabla de compra_ventas?
main_table = pd.read_sql_query("SELECT * FROM main", conn)
main_table.head()

,Date,Close,High,Low,Open,Volume,Empresa,TKT
0,2024-01-02 00:00:00,183.562180,186.330843,181.831767,185.055273,82488700,Apple,AAPL
1,2024-01-03 00:00:00,182.187729,183.799489,181.376900,182.158066,58414500,Apple,AAPL
2,2024-01-04 00:00:00,179.873947,181.040733,178.855477,180.111251,71983600,Apple,AAPL
3,2024-01-05 00:00:00,179.152130,180.714448,178.153440,179.953077,62379700,Apple,AAPL
4,2024-01-08 00:00:00,183.483078,183.522639,179.468523,180.051916,59144500,Apple,AAPL

In [10]:
conn.close()

## Export to csv

In [11]:
main_table.to_csv('../local/csvs/stock_db.csv')

## Conexión con BigQuery

In [12]:
# Generamos conexion a BQ
from google.oauth2 import service_account # para generar conexion con BigQuery
#bq_cred = service_account.Credentials.from_service_account_file('../local/tokens/gcp_token2.json')
bq_cred = service_account.Credentials.from_service_account_file('../local/tokens/gcp_token_clase.json')

bq_cred

In [22]:
# Vemos que hay en "main_table"
main_table = pd.read_csv('../local/csvs/stock_db.csv')
main_table = main_table[['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Empresa', 'TKT']]
main_table.head()

,Date,Close,High,Low,Open,Volume,Empresa,TKT
0,2024-01-02 00:00:00,183.562180,186.330843,181.831767,185.055273,82488700,Apple,AAPL
1,2024-01-03 00:00:00,182.187729,183.799489,181.376900,182.158066,58414500,Apple,AAPL
2,2024-01-04 00:00:00,179.873947,181.040733,178.855477,180.111251,71983600,Apple,AAPL
3,2024-01-05 00:00:00,179.152130,180.714448,178.153440,179.953077,62379700,Apple,AAPL
4,2024-01-08 00:00:00,183.483078,183.522639,179.468523,180.051916,59144500,Apple,AAPL

### Cargar Datos en BQ

In [15]:
# Enviamos el df a BQ - Podemos crear o reemplazar una tabla
import pandas_gbq # para interactuar con BQ

pandas_gbq.to_gbq(main_table, 'ucema_2025.main_from_vs_3', project_id= 'ucema-461612',
                   if_exists= 'replace', credentials = bq_cred)

In [16]:
# Si queremos anexar datos de una tabla en lugar de reemplazar
pandas_gbq.to_gbq(main_table, 'ucema_2025.main_from_vs', project_id= 'ucema-461612',
                   if_exists= 'append', credentials = bq_cred)

### Leer Datos de BQ

In [23]:
# Si queremos leer una tabla
sql = """SELECT * FROM `ucema-461612.ucema_2025.main_from_vs`"""
df_bq = pd.read_gbq(sql, project_id='ucema-461612', credentials = bq_cred, dialect='standard') 

df_bq.head()

/var/folders/7_/kmrlbc594d903fc6dhmzxdrm0000gn/T/ipykernel_46707/3397499726.py:3: FutureWarning: read_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.read_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.read_gbq
  df_bq = pd.read_gbq(sql, project_id='ucema-461612', credentials = bq_cred, dialect='standard')

,Date,Close,High,Low,Open,Volume,Empresa,TKT
0,2024-01-02 00:00:00,183.562180,186.330843,181.831767,185.055273,82488700,Apple,AAPL
1,2024-01-03 00:00:00,182.187729,183.799489,181.376900,182.158066,58414500,Apple,AAPL
2,2024-01-04 00:00:00,179.873947,181.040733,178.855477,180.111251,71983600,Apple,AAPL
3,2024-01-05 00:00:00,179.152130,180.714448,178.153440,179.953077,62379700,Apple,AAPL
4,2024-01-08 00:00:00,183.483078,183.522639,179.468523,180.051916,59144500,Apple,AAPL

In [24]:
df_bq.shape

(2416, 8)